# 配置数据库
HOSTNAME='127.0.0.1'
PORT = '3306'
USERNAME='root'
PASSWORD='rootfjx'
DATABASE='errorcode'
DB_URL=f"mysql+pymysql://{USERNAME}:{PASSWORD}@{HOSTNAME}:{PORT}/{DATABASE}?charset=utf8mb4"
SQLALCHEMY_DATABASE_URI = DB_URL


# 邮箱配置
# 邮箱服务qq、网易、163等等
MAIL_SERVER="smtp.qq.com"
# 是否进行加密
MAIL_USE_SSL = True
# 端口
MAIL_PORT = 465
MAIL_USERNAME="1300448152@qq.com"
# 授权码
MAIL_PASSWORD="bdsoktlirsqwbacc"
MAIL_DEFAULT_SENDER="1300448152@qq.com"

SECRET_KEY="NSLJANLJFNFALNDKVNSDS@#$%RDFGBHT$WM&NBBN&$N"
